baseURL = 'https://dixmax2.github.io/prueba/'
languageCode = 'es'
title = 'PRUEBA'
theme = 'tale'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/main"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0